language: node_js
version: 1.0
node_js:
- lts/*
after_success:
- openssl aes-256-cbc -K $encrypted_edcb9cc328be_key -iv $encrypted_edcb9cc328be_iv -in assets/nasalization-rg.woff.enc -out assets/nasalization-rg.woff -d
- openssl aes-256-cbc -K $encrypted_1a651f550714_key -iv $encrypted_1a651f550714_iv -in assets/Eurostile.woff.enc -out assets/Eurostile.woff -d
- npm run build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: storybook-static
  github_token: $GITHUB_TOKEN
  committer_from_gh: true
  keep_history: true
  on:
    branch: master
